/*
 * KBox-JNIC Core Header — v3 enhanced architecture
 *
 * Defines the shared data structures for the enhanced JNIC interpreter:
 * per-instruction encryption, function-pointer-table dispatch, anti-debug,
 * and execution-time bytecode erasure.
 *
 * This header is embedded inline in kbox_jnic_interp.c by the compiler
 * so it can also be referenced from generated stubs.
 */
#ifndef KBOX_JNIC_CORE_H
#define KBOX_JNIC_CORE_H

#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <setjmp.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- Tagged value union (JVM slot) ---- */
typedef union __attribute__((aligned(8))) {
    jint      i;
    jlong     j;
    jfloat    f;
    jdouble   d;
    jobject   o;
    void*     ptr;
} kbox_slot_t;

/* ---- Exception handler entry (mirrors JVM exception table) ---- */
typedef struct {
    uint32_t start_pc;
    uint32_t end_pc;
    uint32_t handler_pc;
    uint16_t catch_type;  /* constant pool index for exception class */
} kbox_ex_handler_t;

/* ---- Method metadata (generated by obfuscator, read-only in C) ---- */
typedef struct {
    const uint8_t*  code;           /* encrypted bytecode base */
    uint32_t        code_len;
    uint32_t        max_stack;
    uint32_t        max_locals;
    uint32_t        key_seed;       /* per-method decryption key seed */
    uint16_t        ex_count;
    const kbox_ex_handler_t* ex_table;
} kbox_method_t;

/* ---- Runtime stack frame (thread-local, JNI LocalRef managed here) ---- */
typedef struct kbox_frame {
    kbox_slot_t*        locals;       /* local variable array */
    kbox_slot_t*        stack;        /* operand stack */
    uint32_t            sp;           /* stack pointer (slot index) */
    uint32_t            pc;           /* program counter */
    const kbox_method_t* method;      /* current method metadata */
    jmp_buf             ex_buf;       /* exception jump buffer (athrow capture) */
    struct kbox_frame*  next;         /* call chain (for exception unwinding) */
} kbox_frame_t;

/* ---- Instruction handler function pointer type ---- */
typedef void (*kbox_insn_handler_t)(kbox_frame_t* f, JNIEnv* env, void** cp);

#ifdef __cplusplus
}
#endif

#endif /* KBOX_JNIC_CORE_H */
