package com.kbox.core.stringenc;

import com.kbox.core.log.KBoxLog;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldInsnNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.IincInsnNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.InsnNode;
import org.objectweb.asm.tree.IntInsnNode;
import org.objectweb.asm.tree.JumpInsnNode;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.LdcInsnNode;
import org.objectweb.asm.tree.MethodInsnNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.TypeInsnNode;
import org.objectweb.asm.tree.VarInsnNode;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * ZKM-style light obfuscation for the plaintext bootstrap classes.
 *
 * <p>The 6 boot classes ({@code BfSecureLoader}, {@code BfBlobInputStream},
 * {@code NativeLoader}, {@code KbnlKey}, {@code ChaCha20} + its nested
 * {@code Keystream}) ship in plaintext inside the protected jar, so every
 * String literal they carry (payload paths, JNI base names, the KBNL domain
 * seed fragments, library suffixes, error strings) currently sits readable in
 * the constant pool. A heap dump / static read of these classes reveals the
 * bootstrap structure directly.
 *
 * <p>This transform hides those literals and adds minimal control-flow noise:
 *
 * <ol>
 *   <li><b>String encryption</b>: each {@code LDC "..."} String is replaced by
 *       an invocation of a synthetic decryptor with a per-string {@code salt}.
 *       The ciphertext is encoded as a <i>Latin-1 Java String constant</i>
 *       ({@code sbox[byte ^ (i + salt) & 0xff]}, where {@code sbox} is a
 *       <b>per-build</b> random permutation of 0..255 fixed by a build-time seed
 *       and inverted at runtime in the holder's {@code <clinit>}), so no
 *       plaintext byte ever rests contiguously in the constant pool and the same
 *       jar built twice encrypts the same literal to different constants. A
 *       single self-contained holder class (injected as one more bootstrap
 *       entry) owns 2..3 randomized decryptor methods, picked per site — there
 *       is no single stable symbol to patch. Literals of {@value #SPLIT_MIN}+
 *       chars are split into two independently salted constants and re-joined at
 *       the call site, so no single constant holds a whole string. No {@code
 *       byte[]} array constants or surrogate-invalid UTF-16 are produced, so
 *       generated bytecode stays modified-UTF-8 safe and {@code COMPUTE_FRAMES}
 *       clean.</li>
 *   <li><b>Opaque predicates</b>: one provably-taken "always-false" branch is
 *       spliced at the top of each non-native method (boot classes and the
 *       decryptor variants alike), with a dead arithmetic block whose win
 *       targets a label that is never entered — every grammar path joins back to
 *       an empty stack, so the merge expects no stack and {@code COMPUTE_FRAMES}
 *       stays correct.</li>
 * </ol>
 */
public final class BootstrapObfuscator {

    private static final String TAG = "bootobf";
    private final SecureRandom rng = new SecureRandom();
    private final String holder;            // synthetic decryptor owner
    private final String[] decMethods;      // randomized decryptor names
    /** Per-build non-linear mixer: a deterministic Fisher-Yates permutation of
     *  0..255 fixed by {@link #sboxSeed}. The ciphertext in the constant pool
     *  maps each byte through {@link #sbox}; the holder's <clinit> rebuilds the
     *  inverse ({@link #sboxInv}) from the same seed at runtime, so a plaintext
     *  byte only round-trips against THIS build — the same jar built twice
     *  encrypts the same boot string to different constants, and naive
     *  "XOR-and-dump" tooling can no longer recover them. */
    private final long sboxSeed;
    private final int[] sbox;               // forward permutation (build side)
    private final int[] sboxInv;            // inverse permutation (runtime side)
    /** Strings at least this long are split into two independently salted
     *  ciphertext constants, so no single constant holds a whole literal. */
    private static final int SPLIT_MIN = 14;
    private int encrypted;
    private int predicates;

    public BootstrapObfuscator() {
        holder = "com/kbox/runtime/_b" + randomName(12);
        int variants = 2 + rng.nextInt(2);          // 2..3
        decMethods = new String[variants];
        for (int i = 0; i < variants; i++) decMethods[i] = "z" + randomName(9);
        sboxSeed = new SecureRandom().nextLong();
        sbox = permutation(sboxSeed);
        sboxInv = inverse(sbox);
    }

    /** Deterministic Fisher-Yates permutation of 0..255 from a seed.
     *  {@code java.util.Random} is fully specified by the Java language spec,
     *  so build-time (here) and runtime (the holder's <clinit>) derive byte-
     *  identical tables on any JVM. */
    private static int[] permutation(long seed) {
        int[] a = new int[256];
        for (int i = 0; i < 256; i++) a[i] = i;
        Random r = new Random(seed);
        for (int i = 255; i >= 1; i--) {
            int j = r.nextInt(i + 1);
            int t = a[i];
            a[i] = a[j];
            a[j] = t;
        }
        return a;
    }

    private static int[] inverse(int[] p) {
        int[] inv = new int[p.length];
        for (int i = 0; i < p.length; i++) inv[p[i]] = i;
        return inv;
    }

    private static String randomName(int len) {
        final String cs = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        StringBuilder sb = new StringBuilder(len);
        SecureRandom r = new SecureRandom();
        for (int i = 0; i < len; i++) sb.append(cs.charAt(r.nextInt(cs.length())));
        return sb.toString();
    }

    public String holderInternal() { return holder; }

    /** Obfuscates one bootstrap class. @return obfuscated bytes, or raw if unparseable. */
    public byte[] obfuscate(byte[] raw) {
        try {
            org.objectweb.asm.ClassReader cr = new org.objectweb.asm.ClassReader(raw);
            ClassNode cn = new ClassNode();
            cr.accept(cn, org.objectweb.asm.ClassReader.EXPAND_FRAMES
                    | org.objectweb.asm.ClassReader.SKIP_DEBUG);
            encryptStrings(cn);
            // Strip ConstantValue from static final String fields: the LDC usages
            // have been replaced with decryptor calls, but the field's ConstantValue
            // attribute still carries the plaintext string in the constant pool.
            // SKIP_DEBUG above already drops LocalVariableTable/LineNumberTable
            // so local variable names don't leak either.
            for (Object fo : cn.fields) {
                FieldNode fn = (FieldNode) fo;
                if ("Ljava/lang/String;".equals(fn.desc) && fn.value != null) {
                    fn.value = null;
                }
                // Strip the Signature attribute from every field. The Signature
                // carries generic type info (e.g. "Ljava/util/HashMap<Ljava/lang/Integer;[B>;")
                // which is pure reflection metadata — the runtime only needs the
                // erased desc — but it leaks the data structures of the bootstrap
                // classes (HashMap<Integer,byte[]>, Set<Integer>, etc.) to a static
                // reader. Drop it to close that intel channel.
                if (fn.signature != null) fn.signature = null;
            }
            // Strip Signature from methods and from the class itself, plus prune
            // non-essential attribute collections (RuntimeInvisibleAnnotations,
            // RuntimeVisibleAnnotations) that may carry KBox marker annotations.
            if (cn.signature != null) cn.signature = null;
            for (Object mo : cn.methods) {
                MethodNode mn = (MethodNode) mo;
                if (mn.signature != null) mn.signature = null;
                if (mn.visibleAnnotations != null
                        && !mn.visibleAnnotations.isEmpty()) {
                    mn.visibleAnnotations.removeIf(a -> {
                        String d = a.desc;
                        return d != null && d.startsWith("Lcom/kbox/");
                    });
                }
                if (mn.invisibleAnnotations != null
                        && !mn.invisibleAnnotations.isEmpty()) {
                    mn.invisibleAnnotations.removeIf(a -> {
                        String d = a.desc;
                        return d != null && d.startsWith("Lcom/kbox/");
                    });
                }
            }
            // Same pruning for class-level and field-level marker annotations.
            if (cn.visibleAnnotations != null && !cn.visibleAnnotations.isEmpty()) {
                cn.visibleAnnotations.removeIf(a -> {
                    String d = a.desc;
                    return d != null && d.startsWith("Lcom/kbox/");
                });
            }
            if (cn.invisibleAnnotations != null && !cn.invisibleAnnotations.isEmpty()) {
                cn.invisibleAnnotations.removeIf(a -> {
                    String d = a.desc;
                    return d != null && d.startsWith("Lcom/kbox/");
                });
            }
            for (Object fo : cn.fields) {
                FieldNode fn = (FieldNode) fo;
                if (fn.visibleAnnotations != null && !fn.visibleAnnotations.isEmpty()) {
                    fn.visibleAnnotations.removeIf(a -> {
                        String d = a.desc;
                        return d != null && d.startsWith("Lcom/kbox/");
                    });
                }
                if (fn.invisibleAnnotations != null && !fn.invisibleAnnotations.isEmpty()) {
                    fn.invisibleAnnotations.removeIf(a -> {
                        String d = a.desc;
                        return d != null && d.startsWith("Lcom/kbox/");
                    });
                }
            }
            injectPredicates(cn);
            ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
            cn.accept(cw);
            return cw.toByteArray();
        } catch (Throwable e) {
            KBoxLog.warn(TAG, "bootstrap obfuscation failed: " + e + " (falling back to raw)");
            return raw;
        }
    }

    /** Builds the synthetic decryptor holder class (must be injected too).
     *  The holder carries a private static {@code int[] s} = the inverse of the
     *  per-build permutation, rebuilt deterministically in <clinit> from
     *  {@link #sboxSeed}, and the (randomly named) decryptor variants. */
    public byte[] holderBytes() {
        ClassNode hc = new ClassNode();
        hc.version = Opcodes.V1_7;
        hc.access = Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL | Opcodes.ACC_SUPER;
        hc.name = holder;
        hc.superName = "java/lang/Object";
        hc.fields.add(new FieldNode(Opcodes.ACC_STATIC | Opcodes.ACC_PRIVATE,
                "s", "[I", null, null));
        hc.methods.add(clinitMethod());
        for (String m : decMethods) {
            hc.methods.add(decryptorMethod(m));
        }
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
        hc.accept(cw);
        return cw.toByteArray();
    }

    /** {@code static { ... } } rebuilding the inverse permutation from the
     *  build-time seed. Deterministic Fisher-Yates (identical to
     *  {@link #permutation}), so {@code s[perm[i]] == i} for every byte. */
    private MethodNode clinitMethod() {
        MethodNode m = new MethodNode(Opcodes.ACC_STATIC, "<clinit>", "()V", null, null);
        // int[] a = new int[256];
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 256));
        m.instructions.add(new IntInsnNode(Opcodes.NEWARRAY, Opcodes.T_INT));
        m.instructions.add(new VarInsnNode(Opcodes.ASTORE, 0));   // a
        // for (i = 0; i < 256; i++) a[i] = i;
        m.instructions.add(new InsnNode(Opcodes.ICONST_0));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 1));   // i
        LabelNode l0 = new LabelNode();
        LabelNode l1 = new LabelNode();
        m.instructions.add(l0);
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 256));
        m.instructions.add(new JumpInsnNode(Opcodes.IF_ICMPGE, l1));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.IASTORE));
        m.instructions.add(new IincInsnNode(1, 1));
        m.instructions.add(new JumpInsnNode(Opcodes.GOTO, l0));
        m.instructions.add(l1);
        // Random r = new Random(seed);
        m.instructions.add(new TypeInsnNode(Opcodes.NEW, "java/util/Random"));
        m.instructions.add(new InsnNode(Opcodes.DUP));
        m.instructions.add(new LdcInsnNode(sboxSeed));
        m.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "java/util/Random",
                "<init>", "(J)V", false));
        m.instructions.add(new VarInsnNode(Opcodes.ASTORE, 2));   // r
        // for (i = 255; i >= 1; i--) { int j = r.nextInt(i + 1); swap a[i], a[j]; }
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 255));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 1));   // i
        LabelNode l2 = new LabelNode();
        LabelNode l3 = new LabelNode();
        m.instructions.add(l2);
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.ICONST_1));
        m.instructions.add(new JumpInsnNode(Opcodes.IF_ICMPLT, l3));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 2));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.ICONST_1));
        m.instructions.add(new InsnNode(Opcodes.IADD));
        m.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/util/Random",
                "nextInt", "(I)I", false));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 3));   // j
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));    // t = a[i]
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.IALOAD));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 4));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));    // a[i] = a[j]
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 3));
        m.instructions.add(new InsnNode(Opcodes.IALOAD));
        m.instructions.add(new InsnNode(Opcodes.IASTORE));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));    // a[j] = t
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 3));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 4));
        m.instructions.add(new InsnNode(Opcodes.IASTORE));
        m.instructions.add(new IincInsnNode(1, -1));
        m.instructions.add(new JumpInsnNode(Opcodes.GOTO, l2));
        m.instructions.add(l3);
        // int[] inv = new int[256]; for (i = 0; i < 256; i++) inv[a[i]] = i;
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 256));
        m.instructions.add(new IntInsnNode(Opcodes.NEWARRAY, Opcodes.T_INT));
        m.instructions.add(new VarInsnNode(Opcodes.ASTORE, 5));   // inv
        m.instructions.add(new InsnNode(Opcodes.ICONST_0));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 1));   // i
        LabelNode l4 = new LabelNode();
        LabelNode l5 = new LabelNode();
        m.instructions.add(l4);
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 256));
        m.instructions.add(new JumpInsnNode(Opcodes.IF_ICMPGE, l5));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 5));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.IALOAD));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.IASTORE));
        m.instructions.add(new IincInsnNode(1, 1));
        m.instructions.add(new JumpInsnNode(Opcodes.GOTO, l4));
        m.instructions.add(l5);
        // s = inv;
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 5));   // push inv
        m.instructions.add(new FieldInsnNode(Opcodes.PUTSTATIC, holder, "s", "[I"));
        m.instructions.add(new InsnNode(Opcodes.RETURN));
        m.maxStack = 4;
        m.maxLocals = 6;
        return m;
    }

    /** static String d(String cs, int salt) — reconstruct plaintext.
     *  MUST be public: the holder is a separate class, while each string call
     *  site lives in a *different* boot class (NativeLoader, BfSecureLoader, ...).
     *  A private static decryptor trivially throws IllegalAccessError when the
     *  caller resolves across classes; public is also rename-safe (survives
     *  package renaming of the boot set). */
    private MethodNode decryptorMethod(String name) {
        MethodNode m = new MethodNode(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC, name,
                "(Ljava/lang/String;I)Ljava/lang/String;", null, null);
        /* Opaque predicate at entry (always-false, merges to empty stack) so the
         * decryptor itself is not a clean straight-line XOR loop. */
        int pSlot = 5;
        m.instructions.add(new LdcInsnNode(0x1D1B7A5));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, pSlot));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, pSlot));
        m.instructions.add(new InsnNode(Opcodes.ICONST_1));
        m.instructions.add(new InsnNode(Opcodes.IAND));
        m.instructions.add(new InsnNode(Opcodes.ICONST_2));
        LabelNode pAfter = new LabelNode();
        LabelNode pDead = new LabelNode();
        m.instructions.add(new JumpInsnNode(Opcodes.IF_ICMPNE, pAfter));
        m.instructions.add(pDead);
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, pSlot));
        m.instructions.add(new IntInsnNode(Opcodes.BIPUSH, 3));
        m.instructions.add(new InsnNode(Opcodes.IMUL));
        m.instructions.add(new LdcInsnNode(0x9E3779B1));
        m.instructions.add(new InsnNode(Opcodes.IADD));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, pSlot));
        m.instructions.add(pAfter);
        /* int n = cs.length(); char[] c = new char[n];
         * for (int i = 0; i < n; i++)
         *     c[i] = (char)((s[cs.charAt(i) & 0xff]) ^ ((i + salt) & 0xff));
         * return new String(c);  — s is the per-build inverse permutation. */
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));      // cs
        m.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/lang/String",
                "length", "()I", false));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 2));     // n
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 2));
        m.instructions.add(new IntInsnNode(Opcodes.NEWARRAY, Opcodes.T_CHAR));
        m.instructions.add(new VarInsnNode(Opcodes.ASTORE, 3));     // c
        m.instructions.add(new InsnNode(Opcodes.ICONST_0));
        m.instructions.add(new VarInsnNode(Opcodes.ISTORE, 4));     // i
        LabelNode top = new LabelNode();
        LabelNode end = new LabelNode();
        m.instructions.add(top);
        /* for-condition: if (i >= n) break; */
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 4));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 2));
        m.instructions.add(new JumpInsnNode(Opcodes.IF_ICMPGE, end));
        /* c[i] = (char)((s[cs.charAt(i) & 0xff]) ^ ((i + salt) & 0xff)); */
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 3));      // c
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 4));      // i
        m.instructions.add(new FieldInsnNode(Opcodes.GETSTATIC, holder, "s", "[I"));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 0));      // cs
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 4));      // i
        m.instructions.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/lang/String",
                "charAt", "(I)C", false));
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 0xff));
        m.instructions.add(new InsnNode(Opcodes.IAND));
        m.instructions.add(new InsnNode(Opcodes.IALOAD));
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 4));      // (i + salt)
        m.instructions.add(new VarInsnNode(Opcodes.ILOAD, 1));
        m.instructions.add(new InsnNode(Opcodes.IADD));
        m.instructions.add(new IntInsnNode(Opcodes.SIPUSH, 0xff));
        m.instructions.add(new InsnNode(Opcodes.IAND));
        m.instructions.add(new InsnNode(Opcodes.IXOR));
        m.instructions.add(new InsnNode(Opcodes.I2C));
        m.instructions.add(new InsnNode(Opcodes.CASTORE));
        m.instructions.add(new IincInsnNode(4, 1));
        m.instructions.add(new JumpInsnNode(Opcodes.GOTO, top));
        /* return new String(c); */
        m.instructions.add(end);
        m.instructions.add(new TypeInsnNode(Opcodes.NEW, "java/lang/String"));
        m.instructions.add(new InsnNode(Opcodes.DUP));
        m.instructions.add(new VarInsnNode(Opcodes.ALOAD, 3));
        m.instructions.add(new MethodInsnNode(Opcodes.INVOKESPECIAL, "java/lang/String",
                "<init>", "([C)V", false));
        m.instructions.add(new InsnNode(Opcodes.ARETURN));
        m.maxStack = 5;
        m.maxLocals = 6;
        return m;
    }

    @SuppressWarnings("unchecked")
    private void encryptStrings(ClassNode cn) {
        List<MethodNode> ms = cn.methods;
        for (MethodNode mn : ms) {
            if (mn.instructions == null) continue;
            for (AbstractInsnNode ins = mn.instructions.getFirst(); ins != null; ) {
                AbstractInsnNode next = ins.getNext();
                if (ins.getOpcode() == Opcodes.LDC && ins instanceof LdcInsnNode) {
                    LdcInsnNode ldc = (LdcInsnNode) ins;
                    if (ldc.cst instanceof String) {
                        String s = (String) ldc.cst;
                        // ASCII only: the decryptor rebuilds a String from UTF-16
                        // chars, which round-trips single-byte (ASCII/Latin-1) text
                        // exactly but would reinterpret any non-ASCII UTF-8 bytes as
                        // Latin-1. Boot classes carry purely ASCII path/identifier
                        // literals, so the guard is airtight.
                        if (!s.isEmpty() && isAscii(s)) {
                            InsnList repl = new InsnList();
                            if (s.length() >= SPLIT_MIN) {
                                // Split long literals into two independently salted
                                // constants (each possibly via a different decryptor
                                // variant) so no single constant holds the whole
                                // string. concat at the call site.
                                int cut = 6 + rng.nextInt(s.length() - 7); // 6..len-2
                                appendDecrypt(repl, s.substring(0, cut),
                                        decMethods[rng.nextInt(decMethods.length)]);
                                appendDecrypt(repl, s.substring(cut),
                                        decMethods[rng.nextInt(decMethods.length)]);
                                appendConcat(repl);
                            } else {
                                appendDecrypt(repl, s,
                                        decMethods[rng.nextInt(decMethods.length)]);
                            }
                            mn.instructions.insertBefore(ins, repl);
                            mn.instructions.remove(ins);
                            encrypted++;
                        }
                    }
                }
                ins = next;
            }
        }
    }

    private static boolean isAscii(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (s.charAt(i) > 0x7F) return false;
        }
        return true;
    }

    /** Emits one decryptor call: {@code LDC cipher; pushInt salt; INVOKESTATIC
     *  holder.dec(String,int)String}, leaving the plaintext String on the stack. */
    private void appendDecrypt(InsnList l, String s, String decName) {
        int salt = rng.nextInt(256);
        l.add(new LdcInsnNode(encryptLatin1(s, salt, sbox)));
        pushInt(l, salt);
        l.add(new MethodInsnNode(Opcodes.INVOKESTATIC, holder,
                decName, "(Ljava/lang/String;I)Ljava/lang/String;", false));
    }

    /** Joins the two half-decrypts of a split literal. The two decrypt calls ran
     *  left-to-right, so the operand stack (bottom→top) holds {@code
     *  [str_first, str_second]} with {@code str_second} on top. For
     *  {@code INVOKEVIRTUAL String.concat} the receiver is at the bottom of the
     *  stack group and the argument on top, so the stack is already exactly
     *  {@code str_first.concat(str_second)} — no SWAP. (A SWAP here would invert
     *  the halves to {@code str_second.concat(str_first)} and corrupt every
     *  split literal.) */
    private static void appendConcat(InsnList l) {
        l.add(new MethodInsnNode(Opcodes.INVOKEVIRTUAL, "java/lang/String",
                "concat", "(Ljava/lang/String;)Ljava/lang/String;", false));
    }

    /** cipher[i] = sbox[utf8Byte ^ ((i + salt) & 0xFF)] — a per-build non-linear
     *  permutation followed by index-XOR, purely Latin-1 (0..255). MUST mirror the
     *  runtime decryptor, which applies {@code s_inv[cs[i] & 0xff] ^ ((i+salt)&0xff)};
     *  because {@code s} is a permutation and {@code s_inv} its inverse, the two
     *  sides round-trip exactly. The seed fixes {@code s} at build time and the
     *  holder's <clinit> rebuilds {@code s_inv} from the same seed at runtime. */
    private static String encryptLatin1(String s, int salt, int[] sbox) {
        byte[] p = s.getBytes(StandardCharsets.UTF_8);
        char[] c = new char[p.length];
        for (int i = 0; i < p.length; i++) {
            c[i] = (char) (sbox[(p[i] & 0xFF) ^ ((i + salt) & 0xFF)] & 0xFF);
        }
        return new String(c);
    }

    /** Splices one always-false opaque predicate at each non-native method entry.
     *  Constructors and static-init are left untouched to keep the boot path clean. */
    private void injectPredicates(ClassNode cn) {
        for (MethodNode mn : (List<MethodNode>) cn.methods) {
            if (mn.instructions == null) continue;
            if ((mn.access & (Opcodes.ACC_ABSTRACT | Opcodes.ACC_NATIVE)) != 0) continue;
            if (mn.name.equals("<clinit>") || mn.name.equals("<init>")) continue;
            /* int x = 0x1D1B7A5;  if ((x & 1) == 2) { x *= 3 + 0x9E3779B1 } } — x is odd so never. */
            InsnList pre = new InsnList();
            pre.add(new LdcInsnNode(0x1D1B7A5));
            pre.add(new VarInsnNode(Opcodes.ISTORE, mn.maxLocals));
            pre.add(new VarInsnNode(Opcodes.ILOAD, mn.maxLocals));
            pre.add(new InsnNode(Opcodes.ICONST_1));
            pre.add(new InsnNode(Opcodes.IAND));
            pre.add(new InsnNode(Opcodes.ICONST_2));
            LabelNode after = new LabelNode();
            LabelNode dead = new LabelNode();
            pre.add(new JumpInsnNode(Opcodes.IF_ICMPNE, after));   // true (x&1==1 != 2) -> after
            pre.add(dead);                                         // dead path (never taken)
            pre.add(new VarInsnNode(Opcodes.ILOAD, mn.maxLocals));
            pre.add(new IntInsnNode(Opcodes.BIPUSH, 3));
            pre.add(new InsnNode(Opcodes.IMUL));
            pre.add(new LdcInsnNode(0x9E3779B1));
            pre.add(new InsnNode(Opcodes.IADD));
            pre.add(new VarInsnNode(Opcodes.ISTORE, mn.maxLocals));
            pre.add(after);                                       // dead target = join, empty stack
            mn.instructions.insert(pre);
            mn.maxLocals++;
            predicates++;
        }
    }

    private void pushInt(InsnList l, int v) {
        if (v >= -1 && v <= 5) {
            l.add(new InsnNode(Opcodes.ICONST_0 + v));
        } else if (v >= Byte.MIN_VALUE && v <= Byte.MAX_VALUE) {
            l.add(new IntInsnNode(Opcodes.BIPUSH, v));
        } else if (v >= Short.MIN_VALUE && v <= Short.MAX_VALUE) {
            l.add(new IntInsnNode(Opcodes.SIPUSH, v));
        } else {
            l.add(new LdcInsnNode(v));
        }
    }

    public int encrypted() { return encrypted; }
    public int predicates() { return predicates; }
}